title: Book-Style Weekly Newsletter
description: A clean, book-like GitHub Pages newsletter site with categories and Markdown posts.
url: "https://p-prabu.github.io"   # user/org root
baseurl: "/books"                  # project repo name
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: null
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
sass:
  style: compressed
timezone: Europe/Stockholm
home_style: cover  # 'cover' for diary covers, 'notes' for sticky-notes
# Optional branding text on covers (falls back to site.title if unset)
# cover_brand: "Prabu Ponnan"

# Author metadata
author:
  name: "Prabu Ponnan"
  bio: "Sharing weekly notes, experiments, and reflections."
  avatar: "/assets/avatar.jpg"  # optional; add an image at this path to show a photo
  email: ""
  socials:
    twitter: ""
    github: "p-prabu"
    resume: "https://resume.prabuponnan.in/"
    blog: "https://techblog.prabuponnan.in/"
    linkedin: "https://www.linkedin.com/in/prabu-ponnan-ab4803b0/"
