title: Book‑Style Weekly Newsletter
description: A clean, book-like GitHub Pages newsletter site with categories and Markdown posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site, e.g. https://username.github.io
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: null
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
sass:
  style: compressed
timezone: Europe/Stockholm