title: Book-Style Weekly Newsletter
description: A clean, book-like GitHub Pages newsletter site with categories and Markdown posts.
url: "https://p-prabu.github.io"   # user/org root
baseurl: "/books"                  # project repo name
permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: null
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
sass:
  style: compressed
timezone: Europe/Stockholm